import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from 'next/script';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}
        <script src="https://jellyhookapp.vercel.app/tracker.js" data-key="cbf1a6da-544b-4159-95b7-2249f0d5903b"></script>
        <Script src="https://jellyhookapp.vercel.app/tracker.js" data-key="cbf1a6da-544b-4159-95b7-2249f0d5903b"></Script>
        <Script
          src="https://jellyhookapp.vercel.app/tracker.js"
          data-key="cbf1a6da-544b-4159-95b7-2249f0d5903b"
          strategy="afterInteractive"
        />
      </body>
      
      
    </html>
  );
}
