import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from 'next/script';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}
        <script 
          src="http://jellyhookapp.vercel.app/tracker.js" 
         data-key="3f2ea7f1-f04a-4920-b6f1-1cdb2ba5d2a9"
         // strategy="afterInteractive" 
        />
        <Script
          src="https://jellyhookapp.vercel.app/tracker.js"
          data-key="3f2ea7f1-f04a-4920-b6f1-1cdb2ba5d2a9"
          strategy="afterInteractive"
        />
      </body>
      
      
    </html>
  );
}
